version: 2

sources:
  - name: raw
    description: Raw data coming from application databases
    database: MMDEV
    schema: DBT

    tables:
      - name: raw_orders
        description: Orders placed by customers
        config:
          loaded_at_field: order_date
          freshness:
            warn_after:
              count: 6
              period: hour
            error_after:
              count: 24
              period: hour

      - name: raw_payments
        description: Payment transactions
        config:
          loaded_at_field: payment_date
          freshness:
            warn_after:
              count: 1
              period: day
            error_after:
              count: 2
              period: day

      - name: raw_web_events
        description: Website clickstream events
        config:
          loaded_at_field: event_timestamp
          freshness:
            warn_after:
              count: 6
              period: hour
            error_after:
              count: 24
              period: hour

      - name: raw_customers
        description: Customer master data

      - name: raw_refunds
        description: Refund transactions

      - name: raw_web_sessions
        description: Website session-level data

      - name: raw_order_items
        description: Line items for each order

      - name: raw_products
        description: Product catalog data

      - name: raw_marketing_campaigns
        description: Marketing and campaign metadata

      - name: raw_suppliers
        description: Supplier reference data

      - name: raw_coupons
        description: Coupon and discount definitions

